package mon.str.pokemon;

public enum PokemonAbilities { //http://bulbapedia.bulbagarden.net/wiki/Ability
	STENCH("Stench" ,"The stench may cause the target to flinch."),
	DRIZZLE("Drizzle","The Pokémon makes it rain if it appears in battle."),
	SPEEDBOOST("Speed Boost","Its Speed stat is gradually boosted."),
	BATTLEARMOR("Battle Armor","The Pokémon is protected against critical hits."),
	STURDY("Sturdy","It cannot be knocked out with one hit."),
	DAMP("Damp","Prevents the use of self-destructing moves."),
	LIMBER("Limber","The Pokémon is protected from paralysis."),
	SANDVEIL("Sand Veil","Boosts the Pokémon's evasion in a sandstorm."),
	STATIC("Static","Contact with the Pokémon may cause paralysis."),
	VOLTABSORB("Volt Absorb","Restores HP if hit by an Electric-type move."),
	WATERABSORB("Water Absorb","Restores HP if hit by a Water-type move."),
	OBLIVIOUS("Oblivious","Prevents it from becoming infatuated."),
	CLOUDNINE("Cloud Nine","Eliminates the effects of weather."),
	COMPOUNDEYES("Compound eyes","The Pokémon's accuracy is boosted."),
	INSOMNIA("Insomnia","Prevents the Pokémon from falling asleep."),
	COLORCHANGE("Color Change","Changes the Pokémon's type to the foe's move."),
	IMMUNITY("Immunity","Prevents the Pokémon from getting poisoned."),
	FLASHFIRE("Flash Fire","It powers up Fire-type moves if it's hit by one."),
	SHIELDDUST("Shield Dust","Blocks the added effects of attacks taken."),
	OWNTEMPO("Own Tempo","Prevents the Pokémon from becoming confused."),
	SUCTIONCUPS("Suction Cups","Negates all moves that force switching out."),
	INTIMIDATE("Intimidate","Lowers the foe's Attack stat."),
	SHADOWTAG("Shadow Tag","Prevents the foe from escaping."),
	ROUGHSKIN("Rough Skin","Inflicts damage to the foe on contact."),
	WONDERGUARD("Wonder Guard","Only super-effective moves will hit."),
	LEVITATE("Levitate","Gives full immunity to all Ground-type moves."),
	EFFECTSPORE("Effect Spore","Contact may poison or cause paralysis or sleep."),
	SYNCHRONIZE("Synchronize","Passes a burn, poison, or paralysis to the foe."),
	CLEARBODY("Clear Body","Prevents other Pokémon from lowering its stats."),
	NATURALCURE("Natural Cure","All status problems heal when it switches out."),
	LIGHTNINGROD("Lightningrod","Draws in all Electric-type moves to up Sp. Attack."),
	SERENEGRACE("Serene Grace","Boosts the likelihood of added effects appearing."),
	SWIFTSWIM("Swift Swim","Boosts the Pokémon's Speed in rain."),
	CHLOROPHYLL("Chlorophyll","Boosts the Pokémon's Speed in sunshine."),
	ILLUMINATE("Illuminate","Raises the likelihood of meeting wild Pokémon."),
	TRACE("Trace","The Pokémon copies a foe's Ability."),
	HUGEPOWER("Huge Power","Raises the Pokémon's Attack stat."),
	POISONPOINT("Poison Point","Contact with the Pokémon may poison the attacker."),
	INNERFOCUS("Inner Focus","The Pokémon is protected from flinching."),
	MAGMAARMOR("Magma Armor","Prevents the Pokémon from becoming frozen."),
	WATERVEIL("Water Veil","Prevents the Pokémon from getting a burn."),
	MAGNETPULL("Magnet Pull","Prevents Steel-type Pokémon from escaping."),
	SOUNDPROOF("Soundproof","Gives full immunity to all sound-based moves."),
	RAINDISH("Rain Dish","The Pokémon gradually regains HP in rain."),
	SANDSTREAM("Sand Stream","The Pokémon summons a sandstorm in battle."),
	PRESSURE("Pressure","The Pokémon raises the foe's PP usage."),
	THICKFAT("Thick Fat","Ups resistance to Fire- and Ice-type moves."),
	EARLYBIRD("Early Bird","The Pokémon awakens quickly from sleep."),
	FLAMEBODY("Flame Body","Contact with the Pokémon may burn the attacker."),
	RUNAWAY("Run Away","Enables a sure getaway from wild Pokémon."),
	KEENEYE("Keen Eye","Prevents other Pokémon from lowering accuracy."),
	HYPERCUTTER("Hyper Cutter","Prevents other Pokémon from lowering Attack stat."),
	PICKUP("Pickup","The Pokémon may pick up items."),
	TRUANT("Truant","Pokémon can't attack on consecutive turns."),
	HUSTLE("Hustle","Boosts the Attack stat, but lowers accuracy."),
	CUTECHARM("Cute Charm","Contact with the Pokémon may cause infatuation."),
	PLUS("Plus","Ups Sp. Atk if another Pokémon has Plus or Minus."),
	MINUS("Minus","Ups Sp. Atk if another Pokémon has Plus or Minus."),
	FORECAST("Forecast","Castform transforms with the weather."),
	STICKYHOLD("Sticky Hold","Protects the Pokémon from item theft."),
	SHEDSKIN("Shed Skin","The Pokémon may heal its own status problems."),
	GUTS("Guts","Boosts Attack if there is a status problem."),
	MARVELSCALE("Marvel Scale","Ups Defense if there is a status problem."),
	LIQUIDOOZE("Liquid Ooze","Damages attackers using any draining move."),
	OVERGROW("Overgrow","Powers up Grass-type moves in a pinch."),
	BLAZE("Blaze","Powers up Fire-type moves in a pinch."),
	TORRENT("Torrent","Powers up Water-type moves in a pinch."),
	SWARM("Swarm","Powers up Bug-type moves in a pinch."),
	ROCKHEAD("Rock Head","Protects the Pokémon from recoil damage."),
	DROUGHT("Drought","Turns the sunlight harsh if it is in battle."),
	ARENATRAP("Arena Trap","Prevents the foe from fleeing."),
	VITALSPIRIT("Vital Spirit","Prevents the Pokémon from falling asleep."),
	WHITESMOKE("White Smoke","Prevents other Pokémon from lowering its stats."),
	PUREPOWER("Pure Power","Raises the Pokémon's Attack stat."),
	SHELLARMOR("Shell Armor","The Pokémon is protected against critical hits."),
	AIRLOCK("Air Lock","Eliminates the effects of weather."),
	TANGLEDFEET("Tangled Feet","Raises evasion if the Pokémon is confused."),
	MOTORDRIVE("Motor Drive","Raises Speed if hit by an Electric-type move."),
	RIVALRY("Rivalry","Deals more damage to a foe of the same gender."),
	STEADFAST("Steadfast","Raises Speed each time the Pokémon flinches."),
	SNOWCLOAK("Snow Cloak","Raises evasion in a hailstorm."),
	GLUTTONY("Gluttony","Encourages the early use of a held Berry."),
	ANGERPOINT("Anger Point","Maxes Attack after taking a critical hit."),
	UNBURDEN("Unburden","Raises Speed if a held item is used."),
	HEATPROOF("Heatproof","Weakens the power of Fire-type moves."),
	SIMPLE("Simple","The Pokémon is prone to wild stat changes."),
	DRYSKIN("Dry Skin","Reduces HP if it is hot. Water restores HP."),
	DOWNLOAD("Download","Adjusts power according to a foe's defenses."),
	IRONFIST("Iron Fist","Boosts the power of punching moves."),
	POISONHEAL("Poison Heal","Restores HP if the Pokémon is poisoned."),
	ADAPTABILITY("Adaptability","Powers up moves of the same type."),
	SKILLLINK("Skill Link","Increases the frequency of multi-strike moves."),
	HYDRATION("Hydration","Heals status problems if it is raining."),
	SOLARPOWER("Solar Power","In sunshine, Sp. Atk is boosted but HP decreases."),
	QUICKFEET("Quick Feet","Boosts Speed if there is a status problem."),
	NORMALIZE("Normalize","All the Pokémon's moves become the Normal type."),
	SNIPER("Sniper","Powers up moves if they become critical hits."),
	MAGICGUARD("Magic Guard","The Pokémon only takes damage from attacks."),
	NOGUARD("No Guard","Ensures attacks by or against the Pokémon land."),
	STALL("Stall","The Pokémon moves after all other Pokémon do."),
	TECHNICIAN("Technician","Powers up the Pokémon's weaker moves."),
	LEAFGUARD("Leaf Guard","Prevents problems with status in sunny weather."),
	KLUTZ("Klutz","The Pokémon can't use any held items."),
	MOLDBREAKER("Mold Breaker","Moves can be used regardless of Abilities."),
	SUPERLUCK("Super Luck","Heightens the critical-hit ratios of moves."),
	AFTERMATH("Aftermath","Damages the attacker landing the finishing hit."),
	ANTICIPATION("Anticipation","Senses a foe's dangerous moves."),
	FOREWARN("Forewarn","Determines what moves a foe has."),
	UNAWARE("Unaware","Ignores any stat changes in the Pokémon."),
	TINTEDLENS("Tinted Lens","Powers up \"not very effective\" moves."),
	FILTER("Filter","Reduces damage from supereffective attacks."),
	SLOWSTART("Slow Start","Temporarily halves Attack and Speed."),
	SCRAPPY("Scrappy","Enables moves to hit Ghost-type Pokémon."),
	STORMDRAIN("Storm Drain","Draws in all Water-type moves to up Sp. Attack."),
	ICEBODY("Ice Body","The Pokémon gradually regains HP in a hailstorm."),
	SOLIDROCK("Solid Rock","Reduces damage from supereffective attacks."),
	SNOWWARNING("Snow Warning","The Pokémon summons a hailstorm in battle."),
	HONEYGATHER("Honey Gather","The Pokémon may gather Honey from somewhere."),
	FRISK("Frisk","The Pokémon can check a foe's held item."),
	RECKLESS("Reckless","Powers up moves that have recoil damage."),
	MULTITYPE("Multitype","Changes type to match the held Plate."),
	FLOWERGIFT("Flower Gift","Powers up party Pokémon when it is sunny."),
	BADDREAMS("Bad Dreams","Reduces a sleeping foe's HP."),
	PICKPOCKET("Pickpocket","Steals an item when hit by another Pokémon."),
	SHEERFORCE("Sheer Force","Removes added effects to increase move damage."),
	CONTRARY("Contrary","Makes stat changes have an opposite effect."),
	UNNERVE("Unnerve","Makes the foe nervous and unable to eat Berries."),
	DEFIANT("Defiant","When its stats are lowered its Attack increases."),
	DEFEATIST("Defeatist","Lowers stats when HP becomes half or less."),
	CURSEDBODY("Cursed Body","May disable a move used on the Pokémon."),
	HEALER("Healer","May heal an ally's status conditions."),
	FRIENDGUARD("Friend Guard","Reduces damage done to allies."),
	WEAKARMOR("Weak Armor","Physical attacks lower Defense and raise Speed."),
	HEAVYMETAL("Heavy Metal","Doubles the Pokémon's weight."),
	LIGHTMETAL("Light Metal","Halves the Pokémon's weight."),
	MULTISCALE("Multiscale","Reduces damage when HP is full."),
	TOXICBOOST("Toxic Boost","Powers up physical attacks when poisoned."),
	FLAREBOOST("Flare Boost","Powers up special attacks when burned."),
	HARVEST("Harvest","May create another Berry after one is used."),
	TELEPATHY("Telepathy","Anticipates an ally's attack and dodges it."),
	MOODY("Moody","Raises one stat and lowers another."),
	OVERCOAT("Overcoat","Protects the Pokémon from damage from weather."),
	POISONTOUCH("Poison Touch","May poison targets when a Pokémon makes contact."),
	REGENERATOR("Regenerator","Restores a little HP when withdrawn from battle."),
	BIGPECKS("Big Pecks","Protects the Pokémon from Defense-lowering attacks."),
	SANDRUSH("Sand Rush","Boosts the Pokémon's Speed in a sandstorm."),
	WONDERSKIN("Wonder Skin","Makes status-changing moves more likely to miss."),
	ANALYTIC("Analytic","Boosts move power when the Pokémon moves last."),
	ILLUSION("Illusion","Comes out disguised as the Pokémon in back."),
	IMPOSTER("Imposter","It transforms itself into the Pokémon it is facing."),
	INFILTRATOR("Infiltrator","Passes through the foe's barrier and strikes."),
	MUMMY("Mummy","Contact with this Pokémon spreads this Ability."),
	MOXIE("Moxie","Boosts Attack after knocking out any Pokémon."),
	JUSTIFIED("Justified","Raises Attack when hit by a Dark-type move."),
	RATTLED("Rattled","Some move types scare it and boost its Speed."),
	MAGICBOUNCE("Magic Bounce","Reflects status-changing moves."),
	SAPSIPPER("Sap Sipper","Boosts Attack when hit by a Grass-type move."),
	PRANKSTER("Prankster","Gives priority to a status move."),
	SANDFORCE("Sand Force","Boosts certain moves' power in a sandstorm."),
	IRONBARBS("Iron Barbs","Inflicts damage to the Pokémon on contact."),
	ZENMODE("Zen Mode","Changes the Pokémon's shape when HP is halved."),
	VICTORYSTAR("Victory Star","Boosts the accuracy of its allies and itself."),
	TURBOBLAZE("Turboblaze","Moves can be used regardless of Abilities."),
	TERAVOLT("Teravolt","Moves can be used regardless of Abilities.");
	
	private String name, discription;
	
	private PokemonAbilities(String name, String discription) {
		this.name = name;
		this.discription = discription;
	}

	public String getName() {
		return name;
	}

	public String getDiscription() {
		return discription;
	}
	
}
